POST http://localhost:8080/players
Content-Type: application/json

{
  "firstName": "player1",
  "lastName": "name1",
  "position": 1,
  "birthDay": "2014-03-01"
}
###

GET http://localhost:8080/players
Content-Type: application/json

###

GET http://localhost:8080/players/1
Content-Type: application/json

###

DELETE http://localhost:8080/players/2
Content-Type: application/json

###

PUT http://localhost:8080/players
Content-Type: application/json

{
  "id": 3,
  "firstName": "firstName",
  "lastName": "lastName",
  "position": 1,
  "birthDay": "2015-03-01"
}

